In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pylab as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
df=load_iris()

In [4]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.data,df.target)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr=LogisticRegression()

In [9]:
lr.fit(x_train,y_train)

LogisticRegression()

In [10]:
lr.score(x_test,y_test)

0.9736842105263158

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
dc=DecisionTreeClassifier()

In [13]:
dc.fit(x_train,y_train)

DecisionTreeClassifier()

In [14]:
dc.score(x_test,y_test)

0.9473684210526315

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rc=RandomForestClassifier(n_estimators=100)

In [17]:
rc.fit(x_train,y_train)

RandomForestClassifier()

In [18]:
rc.score(x_test,y_test)

0.9736842105263158

In [19]:
from sklearn.svm import SVC


In [20]:
svm=SVC()

In [21]:
svm.fit(x_train,y_train)

SVC()

In [22]:
svm.score(x_test,y_test)

0.9210526315789473

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),df.data,df.target,cv=5)

C:\Users\yash\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [25]:
cross_val_score(DecisionTreeClassifier(),df.data,df.target,cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [26]:
cross_val_score(RandomForestClassifier(),df.data,df.target,cv=3)

array([0.98, 0.94, 0.96])

In [27]:
cross_val_score(SVC(),df.data,df.target,cv=5)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [28]:
rc.score(x_test,y_test)

0.9736842105263158

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
rc=RandomForestClassifier()


In [31]:
rc.fit(x_train,y_train)

RandomForestClassifier()

In [32]:
rc.score(x_test,y_test)

0.9736842105263158

In [33]:
cross_val_score(RandomForestClassifier(),df.data,df.target,cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])